tfs:
    registry-images: "http://localhost:32000/tfs/"
    component:
        - "context"
        - "device"
        - "automation"
        - "monitoring"
        - "pathcomp"
        - "service"
        - "slice"
        - "compute"
        - "webui"
        - "load_generator"
    image-tag: "dev1"
    k8s-namespace: "tfs"
    grafana-password: "admin123+"
    #skip-build: true | false
crdb:
    namespace: "crdb"
    external-ports:
        sql: 26257
        http: 8081
    credentials:
        username: "tfs"
        password: "tfs123"
    database: "tfs"
    deploy-mode: "single"
    #drop-database: true | false
    #redeploy: true | false
nats:
    namespace: "nats"
    external-ports:
        client: 4222
        http: 8222
    #redeploy: true | false
qdb:
    namespace: "qdb"
    external-ports:
        sql: 8812
        ilp: 9009
        http: 9000
    credentials:
        username: "admin"
        password: "quest"
    tables:
        monitoring-kpis: "tfs_monitoring_kpis"
        slice-groups: "tfs_slice_groups"
        #drop-if-exits: true | false
    #redeploy: true | false
service-ports:
    prometheus-http: 9090
    grafana-http: 3000
